version: '3.5'

services:
  app:
    image: php:cli-alpine
    command: ["php", "/var/www/public/index.php"]
    container_name: tuning-app
    volumes:
      - .:/var/www
    sysctls:
      - net.core.somaxconn=${SOCKET_LISTEN_QUEUE}
    ports:
      - "32800:8080"
    networks:
      - tuning-php

networks:
  tuning-php:
    ipam:
      config:
        - subnet: "192.168.80.0/24"
    name: tuning-php