version: '3.5'

services:
  app:
    image: nginx/unit
    container_name: tuning-app
    volumes:
      - .:/www
    sysctls:
      - net.core.somaxconn=${SOCKET_LISTEN_QUEUE}
    ports:
      - "32800:8000"
    networks:
      - tuning-php

networks:
  tuning-php:
    ipam:
      config:
        - subnet: "192.168.80.0/24"
    name: tuning-php